custominventory:
  mapselector:
    itemtype: COMPASS
    enchantment: BINDING_CURSE
    displayname: Map Selector
    namecolor: RED
    slot: 0
    custommodeldata: 1
  friends:
    itemtype: ENCHANTED_BOOK
    enchantment: BINDING_CURSE
    displayname: Friends
    namecolor: DARK_GREEN
    slot: 1
    custommodeldata: 2

gamemodes:
  adventure:
    itemtype: GRASS_BLOCK
    displayname: Adventure Maps
    namecolor: GREEN
    custommodeldata: 1
    index: 0
  puzzle:
    itemtype: BOOKSHELF
    displayname: Puzzle Maps
    namecolor: RED
    index: 1
  parkour:
    itemtype: SLIME_BLOCK
    displayname: Parkour Maps
    namecolor: GREEN
    custommodeldata: 3
    index: 2
  minigames:
    itemtype: GLASS
    displayname: Mini Games
    namecolor: WHITE
    custommodeldata: 4
    index: 3

maps:
  parkour_paradise_3:
    name: Parkour Paradise 3
    gamemode: parkour
    worldname: parkour_paradise_3
    description: Parkour Paradise 3
    difficulty: 6/10
    itemtype: OAK_LOG
    spawnpoint_x: 0
    spawnpoint_z: 0
    spawnpoint_y: 60
    namecolor: RED
    custommodeldata: 1
  parkour_pyramid:
    name: Parkour Pyramid
    gamemode: adventure
    worldname: parkour_pyramid
    description: Parkour Pyramid
    difficulty: 4/10
    itemtype: PAPER
    spawnpoint_x: 0
    spawnpoint_z: 0
    spawnpoint_y: 60
    namecolor: RED
    custommodeldata: 2
  parkour_spiral_2:
    name: Parkour Spiral
    gamemode: Parkour
    worldname: parkour_spiral_2
    description: A fun challenging parkour inside a spiral!
    creator: 
    difficulty: 8/10
    itemtype: GLASS
    spawnpoint_x: -114
    spawnpoint_z: -0
    spawnpoint_y: 113
    namecolor: BLUE
    custommodeldata: 3